package com.vunh.repository;

import com.vunh.entity.Hacker;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

public class HackerRepository {
    public List<Hacker> findAll() {
        List<Hacker> hackers = new ArrayList<Hacker>();
        hackers.add(new Hacker(1, "Nong Hoang Vu", true, "Hacker"));
        hackers.add(new Hacker(2, "Mr Vuz", true, "Hacker"));
        hackers.add(new Hacker(3, "Rose", false, "User"));
        hackers.add(new Hacker(4, "Hacker Vuz", true, "Hacker"));
        hackers.add(new Hacker(5, "Lisa", false, "Security"));
        hackers.add(new Hacker(6, "Bear", false, "Unemployment"));
        hackers.add(new Hacker(7, "Alice", false, "Hacker"));
        hackers.add(new Hacker(8, "Bob", true, "Hacker"));
        hackers.add(new Hacker(9, "Charlie", true, "Hacker"));
        hackers.add(new Hacker(10, "Eve", false, "User"));
        hackers.add(new Hacker(11, "Frank", true, "Hacker"));
        hackers.add(new Hacker(12, "Grace", false, "Security"));
        hackers.add(new Hacker(13, "David", false, "Unemployment"));
        hackers.add(new Hacker(14, "Hannah", true, "Hacker"));
        hackers.add(new Hacker(15, "Ivy", true, "Hacker"));
        hackers.add(new Hacker(16, "Jack", true, "Hacker"));
        hackers.add(new Hacker(17, "Kate", false, "User"));
        hackers.add(new Hacker(18, "Liam", true, "Hacker"));
        hackers.add(new Hacker(19, "Mia", false, "Security"));
        hackers.add(new Hacker(20, "Noah", false, "Unemployment"));
        hackers.add(new Hacker(21, "Olivia", true, "Hacker"));
        hackers.add(new Hacker(22, "Peter", true, "Hacker"));
        hackers.add(new Hacker(23, "Quinn", false, "User"));
        hackers.add(new Hacker(24, "Ryan", true, "Hacker"));
        hackers.add(new Hacker(25, "Sophia", false, "Security"));
        hackers.add(new Hacker(26, "Tyler", false, "Unemployment"));
        hackers.add(new Hacker(27, "Victoria", true, "Hacker"));
        hackers.add(new Hacker(28, "William", true, "Hacker"));
        hackers.add(new Hacker(29, "Xavier", false, "User"));
        hackers.add(new Hacker(30, "Yasmine", true, "Hacker"));
        hackers.add(new Hacker(31, "Zack", true, "Hacker"));
        hackers.add(new Hacker(32, "Amelia", false, "Security"));
        hackers.add(new Hacker(33, "Benjamin", false, "Unemployment"));
        hackers.add(new Hacker(34, "Chloe", true, "Hacker"));
        hackers.add(new Hacker(35, "Daniel", true, "Hacker"));
        hackers.add(new Hacker(36, "Emma", true, "Hacker"));
        hackers.add(new Hacker(37, "Fiona", false, "User"));
        hackers.add(new Hacker(38, "George", true, "Hacker"));
        hackers.add(new Hacker(39, "Holly", false, "Security"));
        hackers.add(new Hacker(40, "Isaac", false, "Unemployment"));
        hackers.add(new Hacker(41, "Jasmine", true, "Hacker"));
        hackers.add(new Hacker(42, "Kevin", true, "Hacker"));
        hackers.add(new Hacker(43, "Lily", false, "User"));
        hackers.add(new Hacker(44, "Michael", true, "Hacker"));
        hackers.add(new Hacker(45, "Natalie", false, "Security"));
        hackers.add(new Hacker(46, "Oscar", false, "Unemployment"));
        hackers.add(new Hacker(47, "Penelope", true, "Hacker"));
        hackers.add(new Hacker(48, "Quincy", true, "Hacker"));
        hackers.add(new Hacker(49, "Rachel", false, "User"));
        hackers.add(new Hacker(50, "Samuel", true, "Hacker"));
        hackers.add(new Hacker(51, "Tiffany", true, "Hacker"));
        hackers.add(new Hacker(52, "Ulysses", false, "Security"));
        hackers.add(new Hacker(53, "Vincent", false, "Unemployment"));
        hackers.add(new Hacker(54, "Wendy", true, "Hacker"));
        hackers.add(new Hacker(55, "Xander", true, "Hacker"));
        hackers.add(new Hacker(56, "Yvonne", false, "User"));
        hackers.add(new Hacker(57, "Zara", true, "Hacker"));
        hackers.add(new Hacker(58, "Adam", true, "Hacker"));
        hackers.add(new Hacker(59, "Bella", false, "User"));
        hackers.add(new Hacker(60, "Chris", true, "Hacker"));
        hackers.add(new Hacker(61, "Diana", true, "Hacker"));
        hackers.add(new Hacker(62, "Ethan", false, "Security"));
        hackers.add(new Hacker(63, "Faith", false, "Unemployment"));
        hackers.add(new Hacker(64, "Gavin", true, "Hacker"));
        hackers.add(new Hacker(65, "Haley", true, "Hacker"));
        hackers.add(new Hacker(66, "Ian", true, "Hacker"));
        hackers.add(new Hacker(67, "Julia", false, "User"));
        hackers.add(new Hacker(68, "Kyle", true, "Hacker"));
        hackers.add(new Hacker(69, "Lena", false, "Security"));
        hackers.add(new Hacker(70, "Mark", false, "Unemployment"));
        hackers.add(new Hacker(71, "Nora", true, "Hacker"));
        hackers.add(new Hacker(72, "Owen", true, "Hacker"));
        hackers.add(new Hacker(73, "Paige", false, "User"));
        hackers.add(new Hacker(74, "Quentin", true, "Hacker"));
        hackers.add(new Hacker(75, "Riley", false, "Security"));
        hackers.add(new Hacker(76, "Samantha", false, "Unemployment"));
        hackers.add(new Hacker(77, "Thomas", true, "Hacker"));
        hackers.add(new Hacker(78, "Uma", true, "Hacker"));
        hackers.add(new Hacker(79, "Violet", false, "User"));
        hackers.add(new Hacker(80, "Wyatt", true, "Hacker"));
        hackers.add(new Hacker(81, "Xena", true, "Hacker"));
        hackers.add(new Hacker(82, "Yolanda", false, "Security"));
        hackers.add(new Hacker(83, "Zane", false, "Unemployment"));
        hackers.add(new Hacker(84, "Abigail", true, "Hacker"));
        hackers.add(new Hacker(85, "Brandon", true, "Hacker"));
        hackers.add(new Hacker(86, "Caroline", false, "User"));
        hackers.add(new Hacker(87, "David", true, "Hacker"));
        hackers.add(new Hacker(88, "Emily", true, "Hacker"));
        hackers.add(new Hacker(89, "Felix", false, "User"));
        hackers.add(new Hacker(90, "Grace", true, "Hacker"));
        hackers.add(new Hacker(91, "Henry", true, "Hacker"));
        hackers.add(new Hacker(92, "Isabella", false, "Security"));
        hackers.add(new Hacker(93, "Jacob", false, "Unemployment"));
        hackers.add(new Hacker(94, "Katherine", true, "Hacker"));
        hackers.add(new Hacker(95, "Liam", true, "Hacker"));
        hackers.add(new Hacker(96, "Mia", true, "Hacker"));
        hackers.add(new Hacker(97, "Noah", false, "User"));
        hackers.add(new Hacker(98, "Olivia", true, "Hacker"));
        hackers.add(new Hacker(99, "Peter", true, "Hacker"));
        hackers.add(new Hacker(100, "Quinn", false, "Security"));
        hackers.add(new Hacker(101, "Ryan", false, "Unemployment"));
        hackers.add(new Hacker(102, "Sophia", true, "Hacker"));
        hackers.add(new Hacker(103, "Thomas", true, "Hacker"));
        hackers.add(new Hacker(104, "Ursula", false, "User"));
        hackers.add(new Hacker(105, "Victor", true, "Hacker"));
        hackers.add(new Hacker(106, "Wendy", true, "Hacker"));
        hackers.add(new Hacker(107, "Xavier", false, "Security"));
        hackers.add(new Hacker(108, "Yara", false, "Unemployment"));
        hackers.add(new Hacker(109, "Zack", true, "Hacker"));
        hackers.add(new Hacker(110, "Alice", true, "Hacker"));
        hackers.add(new Hacker(111, "Bob", false, "User"));
        hackers.add(new Hacker(112, "Caleb", true, "Hacker"));
        hackers.add(new Hacker(113, "Diana", true, "Hacker"));
        hackers.add(new Hacker(114, "Ethan", false, "Security"));
        hackers.add(new Hacker(115, "Fiona", false, "Unemployment"));
        hackers.add(new Hacker(116, "George", true, "Hacker"));
        hackers.add(new Hacker(117, "Hannah", true, "Hacker"));
        hackers.add(new Hacker(118, "Isaac", false, "User"));
        hackers.add(new Hacker(119, "Julia", true, "Hacker"));
        hackers.add(new Hacker(120, "Kevin", true, "Hacker"));
        hackers.add(new Hacker(121, "Lena", false, "Security"));
        hackers.add(new Hacker(122, "Matthew", false, "Unemployment"));
        hackers.add(new Hacker(123, "Natalie", true, "Hacker"));
        hackers.add(new Hacker(124, "Oliver", true, "Hacker"));
        hackers.add(new Hacker(125, "Penelope", false, "User"));
        hackers.add(new Hacker(126, "Quincy", true, "Hacker"));
        hackers.add(new Hacker(127, "Rachel", true, "Hacker"));
        hackers.add(new Hacker(128, "Samantha", false, "Security"));
        hackers.add(new Hacker(129, "Theodore", false, "Unemployment"));
        hackers.add(new Hacker(130, "Ulysses", true, "Hacker"));
        hackers.add(new Hacker(131, "Violet", true, "Hacker"));
        hackers.add(new Hacker(132, "William", false, "User"));
        hackers.add(new Hacker(133, "Xander", true, "Hacker"));
        hackers.add(new Hacker(134, "Yvonne", true, "Hacker"));
        hackers.add(new Hacker(135, "Zoe", false, "Security"));

        return hackers;
    }
}
